In [1]:
%matplotlib qt
%matplotlib notebook
import seaborn as sb
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import threading
import time
from matplotlib import cm



with open('data/q1/linearX.csv') as fp: 
    x=[]
    for line in fp:
        x.append(float(line[:-1]))
#print(X)      
print(len(x))
with open('data/q1/linearY.csv') as fp: 
    y=[]
    for line in fp:
        y.append(float(line[:-1]))


100


In [2]:
X1=np.array(x)
Y1=np.array(y)
X = X1.reshape((X1.shape[0], 1))
Y = Y1.reshape((Y1.shape[0], 1))
thetas= [0,0]

def normalization(X):
    X_mean = np.mean(X)
    X_var= np.sum((X-X_mean)**2)/len(X)
    X_std_dev= np.sqrt(X_var)
    X_norm = (X- X_mean)/X_std_dev
    return X_norm

X_norm1= normalization(X)
X_norm = np.append(np.ones((X_norm1.shape[0], 1)), X_norm1, axis = 1)
theta = np.zeros((2, 1))

def cost(X1, theta1, Y1):
    return np.sum((np.dot(X1, theta1) - Y1) ** 2) /(2* len(Y1))

def grad_cost(X,theta, Y):
    temp = Y-np.dot(X,theta)
    temp2= temp * -X
    theta = (temp2.sum(axis=0))/(len(Y))
    return theta.T.reshape((theta.T.shape[0], 1))
 
def linear_reg(alpha):
    theta = np.zeros((2, 1))
    for i in range(100000):
        gcost=grad_cost(X_norm, theta, Y)
        theta = theta - alpha * gcost
        if i%100==0 :
            thetas.append(theta[0][0])
            thetas.append(theta[1][0])
    return theta



res = linear_reg(0.001)  
print(res)
print(cost(X_norm,res,Y))

thetas=np.array(thetas)
thetas = thetas.reshape(int(thetas.shape[0]/2), 2)



sb.set()
fig, ax = plt.subplots()
a=X_norm[:,1:2]
ax.plot(a,Y,'b^')
# ax.scatter(a,Y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('x-y')
Y_dash =np.dot(X_norm,res)
# print(Y_dash.shape)
plt.plot(a,Y_dash,color='red')
plt.show();

#for surfaceplot
theta0 = np.linspace(0,2, 100)
theta1 = np.linspace(-1,1,100)
Theta0, Theta1 = np.meshgrid(theta0, theta1)
zs = np.array([cost(X_norm,np.array([[i],[j]]),Y) for i,j in zip(np.ravel(Theta0), np.ravel(Theta1))])
Cost = zs.reshape(Theta0.shape)

#for dynamic plot

actual_cost= np.array([cost(X_norm, np.reshape(thetas[i],(2,1)), Y) for i in range(thetas.shape[0])])
print(np.reshape(thetas[0],(2,1)))
print(actual_cost[0])
# print(thetas.shape)
print('Done')
# print(zs.shape)
# print(Cost.shape)

[[0.9966201]
 [0.0013402]]
1.1947898109836603e-06
[[0.]
 [0.]]
0.4966279047145
Done


In [9]:
fig = plt.figure(0)
# ax = fig.add_subplot(211, projection='3d')
ax = plt.axes(projection='3d')
# theta0 = theta1 = np.arange(-3.0, 3.0, 0.05)

# ax.scatter(thetas[:,0:1],thetas[:,1:2],actual_cost, 'ro', alpha=0.5)
ax.plot_surface(Theta0, Theta1, Cost, cmap=cm.coolwarm,linewidth=0,antialiased=False, alpha=0.6)
#Blues
#summer
# YlGnBu
#coolwarm
# print(thetas[:10,0:1].tolist())

line, = ax.plot([],[],[],lw=2)

th0=[thetas[i][0] for i in range(thetas.shape[0])]
th1=[thetas[i][1] for i in range(thetas.shape[0])]
# print(th0[:10])
# print(th1[:10])


def animate(i):
    line.set_data(th0[:i],th1[:i])
    line.set_3d_properties(actual_cost[:i])
    return line,

# line, = ax.plot(th0,th1, actual_cost, lw=2)

# def animate(i):
#     ax.clear()
#     ax.scatter3D(th0[:i], th1[:i],actual_cost[:i])
    

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')


anim = animation.FuncAnimation(fig, animate,frames=200, interval=200,
                           repeat_delay=1, blit=True)
plt.show();


In [4]:
fig2 = plt.figure(2)
ax=plt.axes()
theta0 = np.linspace(0,2, 100)
theta1 = np.linspace(-0.8,1,100)
Theta0, Theta1 = np.meshgrid(theta0, theta1)
ax.contour(Theta0, Theta1, Cost)

line1, = ax.plot([],[],lw=1.5)

def animate2(i):
    line1.set_data(th0[:i],th1[:i])
    return line1,

# ax.plot(th0[:100],th1[:100])
anim2 = animation.FuncAnimation(fig2, animate2,frames=200, interval=200,repeat_delay=5, blit=True)
plt.show();

In [6]:

# theta0 = np.linspace(1,4, 100)
# theta1 = np.linspace(0,2,100)
# theta2 = np.linspace(1,3,100)

fig = plt.figure(0)

ax = plt.axes(projection='3d')
# ax.plot_surface(theta0, theta1, theta2,cmap=cm.coolwarm,linewidth=0,antialiased=False, alpha=0.6)

thetas=np.array(thetas)
print(thetas.shape)
temp = thetas.shape[0]%3
# thetas1 = thetas[:-temp,:]
print(thetas.shape)
thetas = thetas.reshape(int(thetas.shape[0]/3), 3)

th0=[thetas[i][0] for i in range(thetas.shape[0])]
# print(th0.shape)
th1=[thetas[i][1] for i in range(thetas.shape[0])]
th2=[thetas[i][2] for i in range(thetas.shape[0])]
ax.plot(th0, th1, th2)



NameError: name 'theta2' is not defined

In [ ]:
batch size 100 steps 80
e  =0.000009

batch size 

e==0
st

3.508833444386378
33.04083490371704
[[2.99901936]
 [1.0013513 ]
 [1.99859587]]
1.0027394874533802

batch 1000


b size 1000000 steps 1000

63.79644060134888
[[0.00399946]
 [0.01599454]
 [0.00403449]]

b size 1000000 steps 100
6.441242456436157
[[0.00400228]
 [0.01599572]
 [0.00399677